= Recette de pain #001
Bernard Mayer
v1.0, 2020-08-28
:source-highlighter: coderay
//:toc-title: ToC
//:toc: preamble
// Permet que les sections soient numerotees
//:numbered:
:imagesdir: ./img
// :imagedir: ./MOS_Modelisation_UserCode-img


:ldquo: &laquo;&nbsp;
:rdquo: &nbsp;&raquo;

:description: Je ne sait pas encore ce \
    que je vais écrire ici...
    
// ----
// Préambule avant ToC
// ----


// ---------------------------------------------------
== Introduction
Trouvée sur le groupe FB {ldquo}Boulangerie-Patisserie - L'autonomie est la clé de notre futur{rdquo} link:https://www.facebook.com/groups/562905920806655/[https://www.facebook.com/groups/562905920806655/], plus précisément la publication de Jen Jen du 28/08/2020 -> link:https://www.facebook.com/groups/562905920806655/?post_id=1017632662000643[https://www.facebook.com/groups/562905920806655/?post_id=1017632662000643]

A ma demande, il me communique la recette -> link:https://pourquoi-pas-isa.blogspot.com/2015/06/laventure-du-levain-et-la-cuisson-du.html[https://pourquoi-pas-isa.blogspot.com/2015/06/laventure-du-levain-et-la-cuisson-du.html] et me précise :
----
et pour le levain on me l’a donné, je le mets au frigo quand je ne m’en sers pas et je le réactive la veille avec 100g de farine et 100g d’eau ce qui me fait les 200h de la recette
----

== La recette #001
----
lundi 15 juin 2015 +
L'aventure du levain et la cuisson du pain en cocotte
----
=== Note (2019)
Au fil des années, des rencontres et lectures ma façon de faire a évolué vers cette méthode, le pain a une croûte démentielle, croquante, chantante, une mie alvéolée, humide, grasse et équilibrée.  Côté gout des arômes prononcés, plus de caractère et une meilleure conservation. Bien sûr la manière de faire décrite ci-dessous m'a donné satisfaction pendant des années mais apprendre et évoluer pour un mieux est le but de ce blog carnet de cuisine.

=== Texte initial (2015)
Le levain et moi c'est une histoire d'amour qui dure depuis plus de deux ans, je ne t'en ai pas parlé car il me parait difficile de partager ce que je fais "d'instinct", au feeling.  Et puis, avec la récente visite de Mamina, qui a tellement aimé mon pain qu'elle est repartie avec un "bébé" levain, je me suis rendue compte que beaucoup de personnes hésitent à se lancer car trouvent ça compliqué, contraignant et difficile à gérer.  Je vais donc tenter, avec mes mots, de "désacraliser" le truc en t'expliquant ma méthode, simple et qui fait ses preuves.

Sers toi une tasse de café et mets toi bien, ça va être un peu long    ;-)

Merlin, mon premier levain, a été créé en 5 jours (oui, 7 c'est trop long, j'laisse ça à Dieu) avec la méthode du bouquin Pains, c'est lui qui m'a permis, pendant presque un an, d'apprivoiser la bête et de me faire la main sur différentes recettes et techniques.  Merlin n'a malheureusement pas aimé du tout qu'on l'abandonne 4 semaines dans le fond du frigo pour faire le tour de l'Italie, massages, bouche à bouche, menaces, j'ai tout essayé, rien à faire . . .   Merlin repose en paix.

Bien décidée à recréer un nouvel ami, le hasard d'un pique-nique à mis Sylvain et son levain sur ma route, partage du précieux, en route pour de nouvelles aventures.  Baptisé Sylvain (en l'honneur de son papa), mon p'ti bonhomme habite dans un bocal "Le parfait" de 75cl (oui c'est grand, mais après plusieurs tentatives d'évasion, j'ai préféré lui laisser ses aises).  Il vit sur le plan de travail de la cuisine et est nourri tous les jours, car ici ça boulange un jour sur deux. 

=== La nourriture du levain
4-5 cuillères à soupe de farine (blanche, complète, intégrale, blé, froment, seigle, épeautre, ...)  directement dans le pot, puis sous le robinet ajout d'eau, au feeling, touille avec une grande cuillère en bois et referme le pot.  Cette étape prend une minute dix sept secondes, nettoyage de la cuillère compris.  Si tu ne boulange pas tous les jours, tu peux le nourrir un jour sur deux ou sur trois, mais toujours le nourrir la veille de la réalisation d'un pain, qu'il bulle au maximum quand tu en as besoin.

Le levain est vivant, il ne sera jamais le même, un jour liquide comme une pâte à crêpe, un jour épais, c'est à toi, au fur et à mesure des semaines, de choisir son évolution.  Il aura un jour une délicieuse odeur de farine torréfiée, un jour une odeur de vinaigre qui pique au nez.  En fonction de la météo, de la chaleur de la pièce, de la farine utilisée, n'ai pas peur, il est costaud, prêt à tout tenter !!  Je l'aime "liquide" pour préparer les foccacia, ciabatta, pain aux fruits secs, craquelin, en bref les préparations ou tu aimes avoir une mie hyper aéré avec des gros trous et la confiture qui coule.  Je l'aime "épais" pour préparer le pain au quotidien mais aussi pour les brioches, il donne une mie plus serrée qui nous convient bien pour les tartines.

=== La pâte à pain
Préparation 10 minutes, le matin, mais c'est le robot qui fait le travail pendant que tu bois ton café, oui, je suis caféine ô girl    ;-)   

Pose sur ta balance le bol du robot (pour moi c'est le bol en verre du KA, avec le couvercle).  Met 500gr de farine dans le bol  (blanche, complète, intégrale, blé, froment, seigle, épeautre, mélange multi céréales, kamut, orge, maïs, sarrasin, châtaignes, . . .  laisse toi aller, crée ton propre pain, tes mélanges suivant inspiration, contenu du placard, graines, épices, céréales, saison, accord avec le repas prévu)  ajoute dans le bol 200gr de levain et 30cl d'eau.  Met le robot, muni du crochet à pétrir, en marche à vitesse lente.  Après une minute, la boule de pâte est formée, ajoute une cuillère à café de sel et laisse pétrir pendant 7 minutes.  Enlever le bol du robot, mettre le couvercle et déposer le tout dans un endroit tempéré (plan de travail, table de salon, bord de fenêtre, ...) pendant toute la journée.

S'il y a eu un rayon de soleil pendant la journée, la pâte à triplé de volume, touche le couvercle du bol et fait de jolies bulles, ton pain sera aéré.  Si la journée a été sombre, la pâte à doublé mais fait quand même de jolies bulles, ton pain sera plus serré.

=== La cuisson du pain
Préparation 2 minutes, après c'est le four qui bosse.

Prends une cocotte (fonte, verre, acier, céramique,... ce que tu as - pour moi, Pyrex Ø20cm), mets un filet d'huile d'olive dans le fond et étale sur toutes les parois avec un pinceau ou un morceau d'essuie tout.  Avec une corne ramène la pâte en boule et saupoudre là de farine.  Renverse la pâte en une fois dans la cocotte, tranche le dessus du pâton avec une lame (facultatif), mets le couvercle et enfourne dans un four froid.  Allume le four à 230° et laisse cuire une heure.  Au bout de ce temps, sortir la cocotte du four et démouler directement le pain, poser sur une grille et laisser refroidir. 

=== Option
Comme ici on aime les croutes épaisses et croquantes, je remets le pain dans le four 5 minutes à 230° après l'avoir démoulé.  

== Conclusion
Voilà, c'était un peu long mais j'espère t'avoir donné envie de te lancer.  Le pain au levain maison est incomparable, avec un petit peu d'attention et une grosse dose d'amour tu trouveras ta recette "unique".  Et si ce qui te rebute c'est la création du levain, n'hésite pas à laisser un commentaire, quelque soit ta région je suis certaine qu'on trouvera un "papa" levain à partager     :-)

