= Agro : A propos de l'aggradation du sol
Bernard Mayer
v1.0, 2020-09-04: First draft
:source-highlighter: coderay
:sectnums:
:toc: preamble
:toclevels: 4
:toc-title: ToC Agro > Sol > Aggradation
// Permet que la ToC soit numerotee
:numbered:
:imagesdir: ./img
// :imagedir: ./MOS_Modelisation_UserCode-img

:ldquo: &laquo;&nbsp;
:rdquo: &nbsp;&raquo;

:keywords: Resilience Agro
:description: Je ne sait pas encore ce \
    que je vais écrire ici...
    
----
Faire connaissance d'un sol, réparer son éventuelle dégradation.
----


// ---------------------------------------------------

== Faire connaissance avec le sol
Un chapitre spécifique : +
link:./ReconnaitreTypeDeSol/[vers le répertoire dédié]

== Une vidéo YT de ver de terre production 
{ldquo}Les bases des plantes bio-indicatrices{rdquo}
, par le Jardin d'Emerveille +
link:https://www.youtube.com/watch?v=qnamBi4ojBs&feature=youtu.be[]

== Une intervention sur le groupe FB 
link:https://www.facebook.com/groups/MaraichageSolVivant/permalink/2961105390662041/?[] +
Léa Jahan -> Maraichage sol vivant (MSV) +
Bonjour à tous 
A force de lire vos différentes publications et questions/réponses je me rends compte à quel point je suis novice! Du coup plusieurs questions me viennent:
Comment faire un état des lieux de notre terrain? Comment savoir exactement a quelle terre nous avons affaire? J'imagine que c'est la base pour savoir comment la nourrir au mieux. 
Nous sommes dans l'ain en Rhône Alpes,avec donc des gelées l'hiver mais aussi une grande sécheresse l'été.  
A priori je dirais qu'on est sur un terrain argileux,compact.  Entourés de champs pour vaches laitières. 
Voila mon potager n'a pas été une belle réussite cette année je trouve, je cherche donc votre aide de pros ! 
D'un côté on a un potager sur sol,première fois travaillé depuis des années, près d'un cerisier que je soupçonne de pomper toutes les réserves. Et de l'autre nous avons commencé des carrés potager façon permaculture avec matériaux à dispo, grosses branches en dessous puis petits branchages et verdures et enfin de la terre. J'ai jeté quelques pieds de potirons qui ont l'air de s'y plaire. 
C'est un peu fouilli tout ça mais help ! 🤣
Nourrir la terre avec du fumier? ( mélange de crottin de cheval et de foin?) Je ne veux pas spécialement cultiver de légumes d'hiver, que faut il mettre sur le sol en attendant? 

.Arnaud Tilbian
Hello ! Quelques pistes que je peux te proposer 
: étudier les plantes qui poussent spontanément sur ton terrain
, elles sont indicatrices de beaucoup d’élément sur tes sols 
(la bible du domaine 
link: https://www.permaculturedesign.fr/livre-permaculture-encyclopedie-des-plantes-bio-indicatrices-gerard-ducerf-plante-sol/[] ). + 
Une autre approche complémentaire est l'analyse directe de tes sols
 , dont voici une méthodologie 
 link: https://gironde.chambre-agriculture.fr/fileadmin/user_upload/Nouvelle-Aquitaine/100_Inst-Gironde/Documents/pdf_nos_publications/Livret_chambreagricultureA5-compresse.pdf[]

.Sylwi Llems
Étaler du compost meme incompletement décomposé sur des cartons bruns sans encre installés sur le sol. 
Les vers de terre vont travailler la dessous bien au chaud et dans l'humidité tout l'hiver et ameublir le sol et l'enrichir.


== Peut-on faire monter un sol en MO avec seulement des engrais vert ?

link:https://www.facebook.com/groups/MaraichageSolVivant/permalink/3110343849071527/[]

.Romain Tessier
Bonjour, petite question si on ne possède pas les moyens matériels et financier pour faire venir du brf, ou du composte végétal ou de la paille. Peut-on faire monter un sol en MO avec seulement des engrais vert ? Est t'il envisageable en msv d'utiliser seulement des engrais vert ?

les élagueurs se débarassent parfois gratuitement de leur broyat , il n'y a pas besoin de matériel ni d'argent pour en avoir , mais juste des engrais verts marchent oui

c'est possible mais il va te falloir du temps. de plus, tu va devoir maitriser les biomax pour choisir les bons mélanges et savoir les laisser "lignifiés".

Allez chercher du fumier dans les centres équestres

Bien entendu toute la recherche aujourd’hui se situe sur la sélection de plantes qui apportent le maximum de bio masse. On ne peut pas piller les champs du voisins pour faire pousser nos légumes. 

Tout dépend des moyens dont tu parles. J'ai acheté 30m3 de broyat de pommiers à un voisin pour 200€, combien de semences, et à quel prix, aurait il fallu pour produire un équivalent ?
Je ne fais pas d'engrais vert car je n'ai pas de parcelles libres en été, et en hiver, il y a trop peu de production.
La seule solution pérenne et peu coûteuse est la jachère d'herbe spontanée, et l'utilisation de bâches pour la détruire.

Tu ne peux, en aucun cas, comparer brf et biomax.
par contre, les deux sont intimement complémentaire. je ne fait pratiquement jamais un brf sans y implanter un couvert.

Concrètement, je laisserai le terrain jusqu'en mai faire pousser ce que ça veut dessus. Un coup de débroussailleur dedans, et j'y mettrai un maïs direct. Alors soit tes bon et tu le sème en semis direct. Soit tes pas bon comme moi et je passe un coup de motoculteur rapide pas profond juste pour avoir un peu de terre et je sème la dedans.
Le maïs c'est cool, grosse biomasse, tu prend les épis tu laisse tout le reste à ta terre. Après le démarrage du maïs, sème une fabacées aussi. Haricot blanc par exemple qui grimpe sur le maïs.
Variante possible avec du tournesol mais c'est plus délicat au démarrage de la culture.
Une fois prêt, en septembre octobre, tu fou tout ça au sol, et tu jette un seigle ou un blé.
Mois de mai suivant, tu couche tout. Deja la non seulement t'aura fait ton paillage, yaura de la racine aussi. Et dedans tu peut implanter ton potager.
Je conseille de balancer une céréale en fin de saison même si elle te fait pas de grains ça fais de loccupation l'hiver et ça te fait le paillage pour la saison suivante. Peu importe semences naturelles ou non hein.
Ça vaut ce que ça vaut j'ai pas la science en infusion 

Je me suis fait livrer 30m3 de déchets verts broyés pour 80€.
Si t'as la place tu peux cultiver un EV sur une planche sur 2. Sinon, à défaut de place, même en interculture sur tes planches.

Je vise cette piste car je souhaite être autonome en intrants. Je vais planter des arbres qui me feront un apport carboné lors de la taille. Cela va prendre du temps, mais il faut bien commencer à un moment. Je crois même qu'il y en a qui vont la chercher en forêt, mais ça fait du boulot.

Demande au déchetteries moi je récupère du broyat de déchets vert gratuit en caisson de 35m2



== Annexes
link:https://potagerdurable.com/deux-trucs-avec-du-carton-pour-que-votre-potager-resiste-mieux-a-la-chaleur/[] +
link:https://potagerdurable.com/fertilite/[]


