= Resilience / Lire / Zola :: Les Rogon-Macquart
Bernard Mayer
v1.0, 2020-08-03
:toc-title: Table des matières
:toc: preamble
//:imagesdir: ../img

:ldquo: &laquo;
:rdquo: &raquo;

:description: Je ne sait pas encore ce \
    que je vais écrire ici...
    
// ---------------------------------------------------

== Les sources

* Les_Rougon-Macquart, link:https://fr.wikipedia.org/wiki/Les_Rougon-Macquart[(wikipedia)]

.Ce que je cherchais, merci wikipedia !
[options="header,footer"]
|=======================
| N° | Parution | Titre | Date de l'action | Personnage principal des Rougon-Macquart | Génération | Ordre de lecture recommandé par Zola
| 1 | 1871|La Fortune des Rougon| 1851 | Pierre Rougon | 1|1
| 2 | 1872|La Curée| 1852 - 1858 | Aristide Rougon-Saccard | 2|3
| 3 | 1873|Le Ventre de Paris| 1857 - 1858 | Lisa Macquart-Quenu | 2|11
| 4 | 1874|La Conquête de Plassans| 1858 - 1864 | François et Marthe Mouret | 2|6
| 5 | 1875|La Faute de l'abbé Mouret| 1866 | Serge Mouret | 3|9
| 6 | 1876|Son Excellence Eugène Rougon| 1858 - 1861 | Eugène Rougon | 2|2
| 7 | 1877|L'Assommoir| 1850 - 1869 | Gervaise Macquart | 2|13
| 8 | 1878|Une page d'amour| 1854 ? | Hélène Mouret-Grandjean | 2|10
| 9 | 1880|Nana| 1865 - 1870 | Anna Coupeau | 3|17
| 10 | 1882|Pot-Bouille| 1862 - 1863 | Octave Mouret | 3|7
| 11 | 1883|Au Bonheur des Dames| 1864 - 1869 | Octave Mouret  | 3|8
| 12 | 1884|La Joie de vivre| 1862-1869 | Pauline Quenu | 3|12
| 13 | 1885|Germinal| 1866 ? | Étienne Lantier | 3|16
| 14 | 1886|L'Œuvre| 1867 - 1869 | Claude Lantier | 3|14
| 15 | 1887|La Terre| 1860 - 1869 | Jean Macquart | 2|18
| 16 | 1888|Le Rêve| 1860 - 1869 | Angélique Rougon | 3|5
| 17 | 1890|La Bête humaine| 1870 | Jacques Lantier | 3|15
| 18 | 1891|L'Argent| 1864 - 1867 | Aristide Saccard | 2|4
| 19 | 1892|La Débâcle| 1870 - 1871 | Jean Macquart | 2|19
| 20 | 1893|Le Docteur Pascal| 1872 - 1874 |Pascal Rougon et Clotilde Saccard  | 2|20
|=======================
Les dates données pour l'action du roman sont approximatives.

Les romans peuvent se lire de manière indépendante, mais
, pour une meilleure compréhension de la chronologie
, il est préférable de les lire dans l'ordre de parution.
Cependant, Émile Zola aurait recommandé un ordre de lecture différent. 
D'une manière générale, {ldquo}La Fortune des Rougon{rdquo} est le roman d'ouverture qui annonce les principaux personnages de la suite ; 
et {ldquo}Le Docteur Pascal'' en est le bilan final.
Certains romans apparaissent comme des suites : 
{ldquo}La conquête de Plassans{rdquo} débouche sur {ldquo}La faute de l'abbé Mouret{rdquo}
, {ldquo}Pot-Bouille{rdquo} se prolonge par {ldquo}Au Bonheur des Dames{rdquo}
, {ldquo}L'Argent{rdquo} prolonge {ldquo}La Curée{rdquo}
, et {ldquo}La Terre{rdquo} se prolonge par {ldquo}La Débâcle{rdquo}.

== Copier-Coller depuis les sources

=== Les Rougon-macquart par émile Zola

link:https://www.les-rougon-macquart.fr/[]

Plein de trucs dont ce texte introductif 


.*Emile Zola et les Rougon-macquart*

Emile Zola est un écrivain français fondateur du naturalisme en littérature
, dont l'oeuvre principale, les Rougon-Macquart
, est une vaste fresque en vingt volumes qui raconte l'histoire naturelle et sociale d'une famille sous le second Empire. 
Vouant une véritable passion à Honoré de Balzac
, Emile Zola s'inspire de la Comédie Humaine de celui-ci pour construire la fresque romanesque 
 qui restera l'oeuvre d'une bonne partie de sa vie, Les Rougon-Macquart. 
 Dès les premières lignes, Emile Zola a une idée très précise de ce qu'il veut faire même si à l'origine
 , les Rougon-macquart ne devait se tenir que sur dix volumes. 
 Il va confronter dans ces vingt tomes deux familles qui apportent chacune leur caractère
 , leur secret, leur hérédité.
Les Rougon-macquart : la fusion des milieux

Il y a d'abord les Rougon, des commerçants pour la plupart, naviguant dans le monde de la petite bourgeoisie. 
Puis les Macquart, plus proche de la terre, mais aussi volontiers voleurs et de toutes façons, alcooliques. 
Ces branches vont fusionner et donner naissance à divers protagonistes qu'Emile Zola mettra dans toutes les situations possibles
, dans des univers très différents. 
Afin d'étudier l'influence du milieu occupé par chaque personnage sur la destinée de ce dernier
, Emile Zola soulèvera un à un divers pans de la société du Second Empire :
 l'église, le commerce, l'armée, la politique, le monde ouvrier 
 et l'organisation du travail seront autant de prétextes pour analyser ses personnages 
 et observer leur comportement quand ceux-ci sont confrontés aux dures réalités d'un dix-neuvième siècle difficile. 
 Emile Zola se lance donc dans l'écriture des romans qui vont constituer les Rougon-Macquart
 , à raison de trois à cinq pages quotidiennes. 
 Même si le romancier connait un succès certain
 , c'est avec L'Assommoir en 1877 qu'il recueillera ses premiers lauriers mais aussi ses premières haines. 
 On lui reprochera de décrire le monde ouvrier sous un jour beaucoup trop crû. 
 Néanmoins, ce septième roman lui amène gloire et fortune. 
 L'écrivain naturaliste poursuit inlassablement son oeuvre 
et s'attire de nouveau les foudres des critiques avec le neuvième tome des Rougon-macquart
, Nana qui parait en 1880. 
Cette fois-ci, le regard de Zola se porte sur les mondains et surtout leurs vies dissolues incarnées par une jeune fille
, Anna, dont l'occupation première, la prostitution de luxe
, lui permettra de connaitre toute la haute-bourgeoisie du Paris du Second Empire. 
Emile Zola sortira encore deux chefs-d'oeuvre de cette saga
, le grand classique et très documenté Germinal en 1885 
et La Bête Humaine en 1890
, véritable thriller avant l'heure. 
Il clôt cette série romanesque avec Le Docteur Pascal en 1893, dans un calme presque relatif.


_Le naturalisme, dans les lettres, c'est également le retour à la nature et à l'homme
, l'observation directe, l'anatomie exacte, l'acceptation et la peinture de ce qui est._

Emile Zola (1840 - 1902)


=== Les Rougon-Macquart de Zola (Résumé & Analyse)

link:https://databac.fr/pdf/les-rougon-macquart-de-zola-resume-analyse/[]

Extrait :


Il existe, de la main de Zola, un arbre généalogique des Rougon-Macquart, dont chaque rameau est un livre.
Vingt volumes, publiés entre 1871 et 1893 : tel est le vaste cycle des Rougon-Macquart
, qui fait évidemment penserà La Comédie humaine de Balzac.
Le cycle des Rougon-Macquart (vingt volumes) est l'œuvre naturaliste par excellence : 
elle étudie des individus etdes comportements dans des milieux donnés
, et privilégie le réel par rapport à l'imaginaire.Ensemble de vingt romans d'Emile Zola
, publiés entre 1871 et 1893.
Inspiré par la Comédie humaine de Balzac, Zola décide d'entreprendre à son tour une fresque sociale et familiale. 
Ses autres modèles sont Stendhal, Flaubert ou les Goncourt. 
Intéressé par la physiologie et par les théories surl'hérédité du Dr Lucas
, Zola révèle les préoccupations scientifiques et sociales de cette seconde moitié du XIXe siècle positiviste.
Dès 1868, il définit le plan d'ensemble des Rougon-Macquart ; à partir de 1871, il publiera
, à raison d'un roman par an environ, les vingt livres de l'Histoire naturelle et sociale d'une famille sous le Second Empire
, les Rougon-Macquart. 
C'est l'Assommoir qui lui vaut le plus grand succès.
Chacun de ces volumes décrit un pan de la société : le monde de la finance
, les ouvriers, le monde rural, leschemins de fer, etc. 
A chaque fois, Zola prépare son travail par une enquête sociologique scrupuleuse. 
L'ensemble de ce cycle se veut l'illustration de sa doctrine naturaliste : 
chaque être est selon lui déterminé par les circonstances et l'influence de son milieu. 
Aussi le roman devra-t-il retracer l'ensemble des conditions matérielles dans lesquelles évoluent les personnages.
Les oeuvres :

- la Fortune des Rougon (1871) ;
- la Curée (1872) ;
- le Ventre de Paris (1873) ;
- la Conquête de Plassans (1874) ;
- la Faute de l'abbé Mouret (1875) ;
- Son Excellence Eugène Rougon (1876) ;
- l'Assommoir (1877) ;
- Une page d'amour (1878) ;
- Nana (1880) ;
- Pot-Bouille (1882) ;
- Au bonheur des dames (1883) ;
- la Joie de vivre (1884) ;
- Germinal (1885) ;
- l'Oeuvre (1886) ;
- la Terre (1887) ;
- le Rêve (1888) ;
- la Bête humaine (1890) ;
- l'Argent (1891) ;
- la Débâcle (1892) ;
- le Docteur Pascal (1893)

Une œuvre naturaliste.
Il s'agit pour l'auteur d'échafauder une œuvre à la fois littéraire et scientifique ; 
les hommes et la société doivent être observés, analysés
, comme la science examine un organisme et ses divers composants
, tant du point de vue anatomique que physiologique. 
C'est que nous sommes en plein scientisme
, en cette seconde moitié du XIXe siècle où s'illustrent des savants tels que Darwin et Mendel
, mais surtout Claude Bernard, dont Zola a lu L'Introduction à l'étude de la médecine expérimentale (1865). 
S'intéressant donc à  l'hérédité et aux influences du milieu sur les individus, c'est-à-dire au déterminisme
, Zola se propose d'examiner (science) et de raconter (littérature) le destin d'êtres marqués physiologiquement 
et moralement par leurs origines. 
Au début, il y a Adélaïde Fouque (tante Dide), dont le père est mort fou ; 
elle épouse un jardinier (un Rougon) et elle a pour amant un Macquart, ivrogne. 
Ainsi commence la lignée et le cycle des Rougon-Macquart
, l'œuvre marquante du naturalisme :  
la méthode y  est scientifique, et le réel prend le pas sur l'imaginaire.
Vingt ans d'histoire de France.
Les vingt volumes mettent en scène plus de mille deux cents personnages
, et il est évidemment impossible de les résumer ici. 
Cinq d'entre eux ont un statut un peu particulier ; 
ils ne s'inscrivent pas de façon stricte dans l'histoire du second Empire et des Rougon-Macquart mais sont comme des respirations
, hors du temps, sur des thèmes importants pour Zola. 
Il s'agit de :

* La Faute de l'abbé Mouret, 
* Une page d'amour, 
* La Joie de vivre, 
* L'Œuvre et Le Rêve. 

Historiquement, ce vaste cycle couvre toute la période du second Empire (1851-1870) 
et une partie de la IIIe République. 
Il  va donc de La Fortune des Rougon et du coup d'État de Louis Napoléon à  La Débâcle et à l'effondrement de l'Empire
, dans une France qui se prépare à vivre l'affaire Dreyfus. 
Quant au Docteur Pascal -le médecin étant un fils Rougon, déjà présent dans le premier tome-
, il est en quelque sorte l'analyse finale de tout le processus qui a conduit 
à la désagrégation des Rougon-Macquart.


=== Les Rougon-Macquart de Zola : Analyse

link:http://salon-litteraire.linternaute.com/fr/resume-d-oeuvre/content/1849698-les-rougon-macquart-de-zola-analyse[]

*L’Histoire naturelle et sociale d'une famille sous le Second Empire: les Rougon-Macquart*, œuvre maîtresse d'Émile Zola, est, d’après lui, une vaste étude de la société française contemporaine de Napoléon III. La création de cet ouvrage formidable – le mot n’est pas trop fort si on pense au quart de siècle de labeur durant lequel Zola produisit les vingt volumes qui le composent – est dû à une raison née de l’observation de l’état de la littérature au milieu du dix-neuvième siècle. Certes, dans une lettre à Léon Hennique, le maître naturaliste a bien opiné qu’écrire une page de l’histoire sociale de la France, c’était la plus belle chose que pouvait faire un romancier. « C’est à cela, lui a-t-il dit, que nous devons tous mettre notre ambition. » Toutefois, si cette ambition est pour quelque chose dans la naissance des Rougon-Macquart, il faut bien avouer qu’elle l’est pour peu, et que la raison qui doit être tenue pour principale est tout autre. Nous la trouvons facilement en suivant les années de début de l’écrivain naturaliste, période au cours de laquelle nous apercevons son idée directrice, qui avec le temps ira en se précisant.

 

À l’époque où Zola ne compte encore qu’une vingtaine de printemps, de 1859 à 1862, angoissé, inquiet, le futur auteur de l’Assommoir doute de lui-même ; c’est le moment où, après avoir échoué à sa double tentative d’être bachelier, il ne sait de quel côté se tourner. C'est un temps de découragement et de grande misère, durant lequel Guy de Maupassant nous le représente dans sa biographie comme « mangeant à l’occasion, errant à la recherche de la fuyante pièce de cent sous, fréquentant plus souvent le Mont-de-Piété que les restaurants. » Avec tristesse, il se confie dans une lettre à son ami Baille : « Tâcher de se créer un nom littéraire ; certes, c’est le rêve le plus irréalisable que j'aie fait. » Et quand il pense au futur, il en est tout effrayé : « Je pense à l’avenir, et je le vois si noir, si noir, que je recule épouvanté, écrit-il à son camarade Cézanne, pas de fortune, pas de métier, rien que du découragement. »

Pourtant, c’est dans cet état d’esprit et dans l’incertitude où Zola se débat que nous allons voir la première lueur éclairer quelque peu la route qu'il voudrait suivre. Il ne sait encore s’il va persévérer dans la voie des lettres; mais, s’il poursuit, il a un programme qu’il définit ainsi : « Si je prends définitivement la carrière littéraire, j’y veux suivre ma devise : Tout ou rien ! Je voudrais par conséquent ne marcher sur les traces de personne; non que j’ambitionne le titre de chef d’école, – d’ordinaire un tel homme est toujours systématique, – mais je désirerais trouver quelque sentier inexploré et sortir de la foule des écrivassiers de notre temps. »

Ce programme – d’où se dégage déjà une impression de volonté, qualité que posséda à un suprême degré le maître naturaliste – nous donne bien là sa première idée: faire quelque chose de nouveau pour être un grand écrivain. Et, lorsqu’il se sera décidé, de suite il cherchera à prendre des motifs neufs, à s’inspirer d’idées nouvelles ; il est tout empli de l’Avenir. 1789 et 1848 appartiennent au passé, mais ont laissé dans les esprits des traces profondes et modifié sensiblement la société. L’avenir, c’est la liberté, c’est la démocratie en progression, et son âme un peu mystique, mais à coup sûr généreuse, va stimuler sa jeune ardeur et le pousser à écrire l’épopée d’une période troublée par de grandes réactions sociales. Le coup d’État de 1852, le Second Empire, la guerre de 1870 et ses conséquences, quels événements propices, susceptibles d’intéresser un romancier digne de ce nom! D’autre part, Zola aura aussi sa manière, et quelques années plus tard il ajoutera : « L’habileté pour moi ne consiste pas à mentir à sa pensée, à faire œuvre selon le goût ou le dégoût de la foule. L’habileté consiste, l’œuvre une fois faite, à ne pas attendre le public, mais à aller vers lui et à le forcer à vous caresser ou à vous injurier. » C’est la méthode qu’il emploiera.

Presque brusquement, un revirement s’est opéré en lui, et en septembre 1862 « la foi est revenue ». Zola a pris parti ; il croit et espère. Sur une réflexion, il s’est mis au travail ; le jeune débutant s’est dit que les sots parviennent en travaillant ; pourquoi n’essayerait-il pas ce moyen ? C’est alors qu’il finira les Contes de Mai qui seront publiés en 1864 sous le titre de Contes à Ninon. Un an après, son deuxième ouvrage, La Confession de Claude, est prêt à paraître. Ce n’est pas encore la gloire ni la fortune, mais ce sont les premiers pas vers elles. II utilisera la publicité pour se faire connaître, il nous l’a dit : sa méthode consiste à aller vers le public et à le forcer à s’occuper de lui, n’obtiendrait-il même que des injures. Pour cela, Zola fera l’impossible, essayant de créer des incidents à la parution de ses ouvrages, de lancer des polémiques et surtout d’étonner. Lorsqu’il s’adresse à Jules Claretie pour le prier de présenter au public La Confession de Claude, il lui déclare qu’il « tient à être lu avant d’être jugé, préférant un éreintement sincère à quelques mots complaisants ». En effet, quelques mots, même favorables, passeront inaperçus du public, alors qu’un éreintement en bonne et due forme aura plus de chance d’attirer sur lui les regards de la foule. Et c’est d’une plume légère qu’au début de 1866 il informera son ami Valabrègue que maintenant il est rangé parmi « les écrivains dont on lit les œuvres avec effroi ». L’année suivante, à l’éditeur Albert Lacroix, il écrira au sujet de Thérèse Raquin : « Je compte sur un succès d’horreur ». Malgré cela, quelque temps après, le futur auteur des Rougon-Macquart constatera encore avec amertume «  qu’il est dur de faire parler de soi ».


Pendant plusieurs années un désir le poursuit. Lorsqu’il fait le point de la littérature du moment, il voit près de lui les romantiques, et plus près encore ceux que l’on appellera par la suite les naturalistes. Des premiers, dont le genre disparaît et ne lui plaît pas, il n’en reste plus qu’un seul debout, non le moindre il est vrai, puisque c’est Victor Hugo, l’auteur d’Hernani. Des seconds, si le public n’a pas encore apprécié toute la valeur, il n’en reste pas moins qu’ils se nomment Gustave Flaubert et les Goncourt et qu’ils ont leur genre propre. Dans Madame Bovary, Flaubert a poussé très loin l’analyse des caractères et l’observation des détails les plus infiniment petits; les Goncourt ont analysé les choses artistiques et psychologiques dans des volumes que Zola appelle des « œuvres bijoux », et celui qui va devenir le porte-drapeau du naturalisme conclut qu’il n’y a plus rien à faire pour les jeunes qui désirent atteindre le public, que de produire une œuvre importante par la quantité de volumes et la puissance de la création. Là où ses devanciers ont campé un personnage, il créera une famille ; là où ses prédécesseurs ont écrit un livre, il en produira une série. Le romancier veut faire quelque chose d’imposant, « de grandes machines », qui le sortiront, ainsi qu’il le rêve, des écrivassiers de son temps. Lorsqu’il rencontre les Goncourt pour la première fois, en décembre 1868, il les entretient de ce désir, écrire l'histoire d’une famille, ouvrage en plusieurs volumes dans lequel il montrera le jeu des tempéraments, des vices et des vertus, modifié par l’hérédité et le milieu.


Ainsi donc, sa première idée se développe et son projet prend forme. Il précise même que son histoire com­portera huit volumes. Mais, dans tout cela, il y a une influence qui joue un grand rôle. C’est Honoré de Balzac. En effet, il ne faut pas oublier que Zola parlera et reparlera toujours du pauvre écrivain et poète français à deux francs la page – comme s’intitulait tristement Balzac lui-même. Il est obligé de reconnaître que l’auteur de la Comédie Humaine l’incite à faire comme lui. Que ce soit au sujet de roman, théâtre, méthode expérimentale, toujours il aura recours à celui qui écrivit les Contes drolatiques, qui, pour lui, écrase tout son siècle, et efface même Victor Hugo et les autres romantiques. « Je ferai, dira-t-il en parlant du Second Empire, à un point de vue plus méthodique ce que Balzac a fait pour le règne de Louis-Philippe ». C’est son maître et il l’avoue, comme au demeurant celui de tous les naturalistes, car il suffit que Balzac « ait le premier affirmé l’action décisive du milieu sur le personnage, qu’il ait porté dans le roman les méthodes d’observation et d’expérimentation ». Toutefois, esprit plus systématique, au lieu de partir sans plan comme le fit son malheureux devancier – qui ne songea à réunir par un lien les divers ouvrages qu’il appela la Comédie Humaine, qu’après coup, en 1833 –, Zola, au contraire, a un projet bien déterminé qui mûrit dans sa tête. En 1870, au cours d’une nouvelle rencontre avec Edmond de Goncourt, il l’informe que son histoire comprendra maintenant dix volumes.

 

Dans ses notes, Zola nous indique ce que seront les Rougon-Macquart : « Pour résumer mon œuvre en une phrase, je veux peindre, au début d’un siècle de vérité et de liberté, une famille qui s’élance vers les biens prochains et qui roule, détraquée par son élan lui-même, justement à cause des lueurs troubles du moment, des convulsions fatales de l'en­fantement d’un monde. »

 

Tout d’abord, il prévient qu’il n’établira ou ne défendra de système politique ou religieux. Comme Flaubert et les Goncourt, il entend simplement montrer les actes humains, impersonnellement, en tenant compte cependant du fameux milieu et de l’hérédité, deux agents mo­dificateurs dont peu de romanciers s’étaient préoccupés jusque-là. Le résultat qu’il désire que son histoire obtienne est le suivant: « Dire la vérité, démonter notre machine, en montrer les secrets ressorts par l'hérédité, faire voir le jeu des milieux. » Ce n’est plus de la psychologie, c’est de la physiologie ! Il ne veut point écrire en philosophe ou en moraliste – plus tard il dira le contraire – et voici où il précise toute sa pensée : « Mes livres seront de simples procès-verbaux. » Une idée le poursuit et le harcèle: surtout ne pas faire comme les autres. Nous avons déjà vu que, dès ses débuts littéraires, cette pensée dominait chez lui. Il y revient : « Tout le monde, remarque-t-il, réussit en ce moment l’analyse du détail ; il faut réagir par la construction solide des masses des chapitres ; par la logique, la poussée de ces chapitres se succédant comme des blocs de pierre superposés, se mordant l’un l’autre ; par le souffle de passion dominant le tout, courant d’un bout à l’autre de l’œuvre. »

Zola ne veut point être accusé de copier ses aînés et il reprend : « Les Goncourt seront si bien écrasés par la masse (par la longueur des chapitres, l’haleine de la passion et la marche logique) qu’on n’osera pas m’accuser de les imiter. »

 

De plus, le jeune romancier entend faire œuvre d’homme de science, et c’est ce qui, d’après lui, le différenciera de Balzac : « Mon œuvre sera moins sociale que scientifique ; au lieu d’avoir des principes (la royauté, le catholicisme) j’aurai des lois (l’hérédité, l’innéité). Je ne veux point, comme Balzac, avoir des décisions sur les affaires des hommes, être philosophe, moraliste. Je me contenterai d’être savant. »

Savant? Voilà bien le mot lâché, mot qu’il allait répéter au cours de ses articles et qui fit tant rire Guy de Maupassant. C’est qu’en effet, ainsi qu’il nous le dit ci-dessus, Zola désire être un écrivain scientifique. À l’instar de Claude Bernard et de Taine, il aura sa méthode. Claude Bernard a tracé la méthode concernant la physiologie ; Taine a montré la voie méthodique relative aux arts et professé que l’avancement des sciences en général assure aux sciences morales le même progrès et la même solidité qu’aux sciences naturelles. D’une façon non moins catégorique, ce dernier affirma également que les productions de l’esprit humain, comme celles de la nature, ne s’expliquent que par leur milieu. En 1865 est parue l’Introduction à l’étude de la médecine expérimentale et la Philosophie de l’Art. Le maître naturaliste en subit l'influence, et c’est dans cette atmosphère que Zola, qui prétend que sa génération est malade de progrès et avide de science, s’empare de ces nouvelles idées pour en faire une application qui portera à faux et réjouira très fort ses ennemis. En politique comme en roman, en morale aussi bien qu’au théâtre, en sociologie de même qu’en économie politique, et jusque dans la poésie et la critique, il prêchera sa théorie et essayera de l’implanter, fermement convaincu qu’elle triomphera partout.

Cette méthode expérimentale, dont il nous entretiendra souvent au long de ses études littéraires, l’auteur de l’Assommoir l’explique en ne faisant, comme il l’indique lui-même « qu’un travail d’adaptation » de l’ouvrage qui l’a le plus séduit, c’est-à-dire l'Introduction à l’étude de la médecine expérimentale de Claude Bernard. Il applique les deux définitions « d’observateur » et « d’expérimentateur » du savant physiologiste, définitions scientifiques par excellence, au romancier. Le plus souvent, il lui suffira, nous annonce-t-il, « pour rendre sa pensée plus claire et lui apporter la rigueur d’une vérité scientifique », de remplacer le mot « médecin » par celui de « romancier ». Une sentence l’avait beaucoup frappé; Claude Bernard n’avait-il pas écrit: « L’expérimentateur est le juge de la nature » ? Aussi Zola en est tout naturellement amené à déduire que « nous autres romanciers, nous sommes les juges d’instruction des hommes et de leurs passions », et « qu’il est indéniable que le roman naturaliste, tel que nous le comprenons à cette heure, est une expérience véritable que le romancier fait sur l’homme en s’aidant de l’observation ». Dans la chaleur de la discussion, et avec toute la fougueuse ardeur qui l’anime, l’auteur des Rougon-Macquart déclare tout bonnement qu’il en est arrivé à cette conclusion, tant de fois rappelée, à savoir que « le roman expérimental est une conséquence de l’évolution scientifique du siècle, il continue et complète la physiologie, qui, elle-même s’appuie sur l’étude de la chimie et de la physique ». Aussi nettement, il proclamera que les romanciers naturalistes ont derrière eux la science, et qu’il ne veut point polémiquer avec ses adversaires parce qu’il n’est qu’un « moraliste expérimentateur », « qu’un savant et qu’un observateur », pour lequel quiconque est avec la science doit être avec lui. Évidemment, Zola se rend bien compte que, malgré tout, ce n’est point les certitudes de la chimie ou de la physiologie, mais, rappelle-t-il, le roman expérimental est plus jeune que la médecine expérimentale, et ce n’est point parce que l’on ne connaît pas encore « les réactifs qui décomposent les passions et permettent de les analyser », qu’il faut en conclure que cette science n’existe pas. La prétention du maître naturaliste à se qualifier de savant donna lieu à une gausserie générale. Ses amis eux-mêmes ne purent tenir leur sérieux. Dans une lettre à Gustave Flaubert, Guy de Maupassant ne se cache pas pour lui faire part du jugement sévère qu’il porte sur Zola en cette occasion : « Que dites-vous de Zola? lui écrit-il, moi je le trouve absolument fou... — Je ne suis qu’un savant — !!! (rien que cela ! quelle modestie!) — Je ne suis qu'un savant — !!! Cela est pyramidal!!! et on ne rit pas... »

 

D’un autre côté, Zola est un amateur de vie. Pour lui, le monde n’est qu’une succession ininterrompue de fresques vivantes et il regrette « de ne pouvoir vivre toujours pour assister à l’éternelle comédie aux mille actes divers ». L’artiste, il le criera bien haut dès ses premières critiques, doit être entièrement libre de chercher, dans la nature humaine dénudée, tout ce qui lui semble nécessaire pour décrire avec précision les actions de ses contemporains. Et s’il rejette toute contrainte de la morale, c’est qu’il pense que l’art purifie tout, comme le feu. Tout de suite, le jeune écrivain s’était senti attiré par certains romans. À l’apparition de Germinie Lacerteux, en 1865, il déclara que son tempérament le portait à admirer fortement l’œuvre des Goncourt. Écoutons ce qu’il nous en dit ; ce jugement nous donne là une idée de ce que pouvait être son goût à cette époque, qui est celle de sa vingt-cinquième année : « Je trouve en elle les défauts et les qualités qui me passionnent : une indomptable énergie, un mépris souverain du jugement des sots et des timides, une audace large et superbe, une vigueur extrême de colori et de pensée, un soin et une conscience artistiques rares en ces temps de productions hâtives et mal venues. Mon goût, si l’on veut, est dépravé ; j’aime les ragoûts littéraires fortement épicés, les œuvres de décadence où une sorte de sensibilité maladive remplace la santé plantureuse des époques classiques. Je suis de mon âge. »

En vérité, ces lignes constituent une déclaration de foi qui guidera la création des Rougon-Macquart. Pour Zola, l’art n’est point comme chez Flaubert le summum de ses désirs. Son état d’esprit pseudo-scientifique le pousse à nous avertir que ce qu’il veut, c’est que « le romancier se dise avant tout qu’il est un physiologiste et un psychologue ».

 

Les plans qui figurent dans ses notes montrent, dans une certaine mesure, le développement de son projet initial. Nous savons déjà, par les déclarations que Zola fit aux Concourt en 1868, que son histoire devait comprendre huit volumes, et, en 1870, que le nombre de ces volumes était porté à dix. En effet, la première liste comporte bien les dix romans suivants à écrire : Un roman sur les prêtres (Province) ; Un roman militaire (Italie) ; Un roman sur l’art (Paris) ; Un roman sur les grandes démolitions de Paris ; Un roman judiciaire (Paris) ; Un roman ouvrier (Paris) ; Un roman dans le grand monde (Paris) ; Un roman sur la femme d’intrigue dans le commerce (Paris) ; Un roman sur la famille d’un parvenu (effet de l’influence de la brusque fortune d’un père sur ses filles et garçons) (Paris) ; Roman initial (Province).

 

L’écrivain nous laisse savoir que son dessein était de publier deux volumes chaque année, de façon à terminer son histoire en cinq ans. Mais il avait compté sans la nombreuse progéniture des Rougon et, le sujet l’entraînant malgré lui, son champ d’action s’élargit. Quelques années après, il établit une seconde liste des livres à écrire qui s’élèvent à dix-sept.

Zola mettra son intention à exécution et, en juin 1870, Le Siècle commencera la publication de La Fortune des Rougon, « qui doit s’appeler de son titre scientifique : les Origines ». Lorsque ce roman paraîtra en librairie l’année suivante, on pourra lire dans la préface : « Les Rougon-Macquart, le groupe, la famille que je me propose d’étudier, a pour caractéristique le débordement des appétits, le large soulèvement de notre âge, qui se rue aux jouissances. Physiologiquement, ils sont la lente succession des accidents nerveux et sanguins qui se déclarent dans une race, à la suite d’une première lésion organique, et qui déterminent selon les milieux, chez chacun des individus de cette race, les sentiments, les désirs, les passions, toutes les manifestations humaines naturelles et instinctives, dont les produits prennent les noms convenus de vertus et de vices. Historiquement, ils partent du peuple, ils irradient dans toute la société contemporaine, ils montent à toutes les situations, par cette impulsion essentiellement moderne, que reçoivent les basses classes en marche à travers le corps social, et ils racontent ainsi le Second Empire, à l’aide de leurs drames individuels, du guet-apens du coup d’État à la trahison de Sedan. »

 

Premier livre d’une série qui devra finalement en compter vingt, ce ne sera que vingt-deux ans après que cette œuvre importante se terminera par le Docteur Pascal, « résumé et conclusion » de l’Histoire des Rougon-Macquart et qui lui aura donné beaucoup de mal, d’après ses dires, afin que son ouvrage ait « quelque chose du serpent qui se mord la queue ».

 

Presque tous ses romans seront d’un naturalisme brutal, « féroce » même, ainsi qu’il le qualifiera lui-même, et on pourra à juste titre leur reprocher l’effet qu’ils produisent, effet voulu et qu'il a personnellement jugé en disant des œuvres des naturalistes: « Elles révoltent, elles ne séduisent pas ». Et si l’on veut l’explication de la manière de procéder de l’auteur de l’Assommoir, on la trouvera dans l’idée qu’il a exprimée, à savoir que « la note douce ne permet aucun effet ». C’est pourquoi il essayera toujours de s’en tenir aux deux règles qu’il a posées dès le début de sa carrière littéraire : exception et drame. Il nous explique ses raisons ; écoutons ce qu’il nous dit au sujet de l’exception : « Dans les études que je veux faire, je ne puis guère sortir de l’exception. Ces créations particulières sont, d’ailleurs, plus d’un artiste, ce mot étant pris dans le sens moderne. Il semble aussi qu’en sortant du général, l’œuvre devient supérieure ; il y a création d’homme, effort d’artiste. L’œuvre gagne en intérêt humain ce qu’elle perd en réalité courante. Il faudrait donc faire exceptionnel comme Stendhal, éviter les trop grandes monstruosités, mais prendre des cas particuliers de cerveau et de chair. »

Quant au drame, ses considérations sont les suivantes : « Ne pas oublier que le drame prend le public à la gorge. Il se fâche, mais n’oublie plus. Lui donner toujours, sinon des cauchemars, au moins des livres excessifs qui restent dans sa mémoire. Il est inutile d’ailleurs de s’attacher sans cesse aux drames de la chair. Je trouverai autre chose d’aussi poignant. »

 

Ce qu'il y a de réellement remarquable chez cet écrivain, c’est qu’établissant le plan de l’Histoire des Rougon-Macquart en 1868, il le réalisera sans dévier jusqu’au dernier livre, qui paraîtra en 1893. Pendant vingt-cinq ans, il suivra la route qu’il s’est tracée, ne changeant sa méthode malgré les clameurs hostiles de ses contemporains, et s’efforçant continuellement de faire fort, exceptionnel et dramatique. Une seule fois peut-être cherchera-t-il à plaire au public ; ce sera lorsqu’il écrira Une page d’amour, dont le sujet paisible surprendra bien fort la critique, nullement habituée à voir Zola produire de pareils livres. L’auteur lui-même, au demeurant, en sera presque étonné et mécontent, pensant que la foule ne peut se passionner pour un roman aussi calme.

Certes, ainsi qu’il le prévoyait, le monde se fâcha. Il est assez curieux, maintenant, de lire les critiques qui saluèrent la publication de ses livres. Le mépris, l’injure, la haine, le parti pris politique fournirent le plus souvent les éléments principaux des jugements de ses contemporains. Mais, au fond, Zola devait être, sinon satisfait, tout au moins content. II avait atteint le but désiré, c’est-à-dire écrit une œuvre importante et puis­sante qui le sortait des écrivassiers de son temps, œuvre dont chaque livre, une fois lu, demeure dans la mémoire, non par la finesse ni la délicatesse qu’il comporte, mais par le côté exceptionnel et impressionnant. Et, on pourrait, au sujet de l’Histoire des Rougon-Macquart, rappeler ce que Flaubert écrivit lorsque parut le premier volume de cette célèbre série: « C’est un atroce et beau livre. C’est fort ! Très fort ! »
 

_Jean Riental, Mercure de France n°882, 15 mars 1935_

